### ISSUE TITLE
yast firstboot loop

### ISSUE THREAD

**Issue by aspiers** [cseader/suse-cloud-appliances#10]
I managed to create an appliance which forever does the firstboot thing and then switches to runlevel 0 ...

**Comment by cseader** [comment]
I still have never run into this loop. I do however run into this loop if there is a termination of sorts along the way and the final script is not allowed to do its cleanup.

**Comment by aspiers** [comment]
Well I still have the VM so if you can suggest a way of debugging it I can try that.

**Comment by cseader** [comment]
Send me the /var/log/prepare-admin.log after the looping is over so I can see if the cleanup finished and where it may have failed.

**Comment by aspiers** [comment]
The looping doesn't stop and none of the normal [YaST tricks](https://en.opensuse.org/SDB:YaST_tricks) work :-/

**Comment by cseader** [comment]
Waiting for you to try the 1.1 milestone built images before debugging. Seems like an isolated case here.

**Comment by aspiers** [comment]
OK :)

**Comment by aspiers** [comment]
Downloading ...

**Comment by aspiers** [comment]
BTW can I recommend that you follow http://semver.org/ for choice of version numbers?  (Maybe you already were, not sure.)

**Comment by cseader** [comment]
I have changed things as best I can to follow semver.org

Adam, have you had this loop in the latest build?

**Comment by aspiers** [comment]
On 25 April 2014 00:04, Cameron Seader notifications@github.com wrote:

> I have changed things as best I can to follow semver.org
> 
> Adam, have you had this loop in the latest build?

No I haven't tried it yet due to the confusion with the download.

**Comment by cseader** [comment]
Nothing to do on this as I have not seen it creep up.

**Comment by cseader** [comment]
Closing as there is a new appliance and I think this is irrelevant.
