### ISSUE TITLE
default to sensible hostname

### ISSUE THREAD

**Issue by aspiers** [cseader/suse-cloud-appliances#18]
With 1.1.0 it's defaulting to a random hostname and domain name `site`.  It also defaults to changing hostname via DHCP, which we don't want.

**Comment by aspiers** [comment]
I suggest `cloud3-admin` or `suse-cloud-3-admin` (but that might be too long).

**Comment by cseader** [comment]
I'll change the host name from admin to cloud-admin. Looking into disabling the change of host name via DHCP.
