### ISSUE TITLE
don't duplicate unless you really have to

### ISSUE THREAD

**Issue by aspiers** [cseader/suse-cloud-appliances#19]
This golden rule applies everywhere ;-)  But the example I am thinking of right now is these new `suse-cloud-[34]-admin` hierarchies.  The industry standard way of dealing with different releases is to use git branches.  This brings huge advantages because you can use all the tools in the git ecosystem for managing the branches separately (and in tandem) for standard tasks like comparing, porting, tagging.  In contrast, with the current approach you have to do all this stuff manually, and it leads to other ugliness like not being able to restrict `git log` to commits which only affect Cloud 3 appliances.

So unless there is a really compelling to do this, I'd much prefer to have two branches.  I suggest `suse-cloud-3` for Cloud 3 and `master` for Cloud 4.

**Comment by cseader** [comment]
Changed.. my ignorance here. I have learned branching now. Thanks for the mentoring. Again. ;-)
