### ISSUE TITLE
don't require NCC / SMT registration by default

### ISSUE THREAD

**Issue by aspiers** [cseader/suse-cloud-appliances#2]
By default the appliance should work without any NCC / SMT registration, to keep the barrier to entry as low as possible.  Of course it should still support NCC / SMT setup, but only as a non-intrusive option.

**Comment by aspiers** [comment]
Ah, I see that the NCC yast module has a "Configure Later" option right at the top so that's already not too bad.  The SMT module allows the Enabling checkbox to be unticked, but it still insists on the fields being populated which is dumb.  Perhaps a yast bug should be filed for that.

**Comment by aspiers** [comment]
What's the latest on this?

**Comment by fghaas** [comment]
To clarify: even if you set NCC to "Configure Later", disable SMT, and set a bogus username and password to work around what @aspiers mentioned earlier, the install eventually spins for a really long time on  the _Prepare SUSE Cloud 3 Admin: Setup SMT repos_ step. It eventually does seem to complete, but only after hitting an avoidable timeout.
