### ISSUE TITLE
embedded preload iso v1.2.0 fails during install of ipmitools

### ISSUE THREAD

**Issue by bwgartner** [cseader/suse-cloud-appliances#20]
Noticed on several runs, that screen install-suse-cloud errors. In the log, complains of not being able to install ipmitools. With login to system, one can easily search for and find this package, then install-suse-cloud proceeds to completion

**Comment by cseader** [comment]
Is this on the Embedded or Standard or Both?

**Comment by cseader** [comment]
Nevermind, I need to learn how to read. ;-)
