### ISSUE TITLE
v1.2.0 incorrectly registers SUSE-Cloud-3-Updates repostiory

### ISSUE THREAD

**Issue by bwgartner** [cseader/suse-cloud-appliances#21]
The path of the repository is registered as /SUSE-Cloud-3-Updates and as an ISO.  This causes screen install-suse-cloud to apprently hang at that step indefinitely. Correcting this with a login to the system via YaST/Software Repositories by deleting errant entry and pointing to a local directory under /srv/tftpboot/repos/SUSE-Cloud-3-Updates allows the process to complete

**Comment by cseader** [comment]
Found the error. There was a missing variable.. must have missed that when testing  and moving things around.
