### ISSUE TITLE
switch huge .tar files to overlays

### ISSUE THREAD

**Issue by aspiers** [cseader/suse-cloud-appliances#25]
Currently the 1GB .tar files are concatenated and unpacked when the appliance is first booted.  This is dumb ;-)  It means firstboot is really slow, and also it wastes a TON of disk space.

Instead we should make .tar.bz2 files which are overlays, i.e. they get unpacked directly into the appliance's `/` filesystem at _build_ time.  I think it would make sense to have one .tar.bz2 per repo, e.g. `SLES11-SP3-Updates.tar.bz2`.

Also, we need a simple script which generates these overlay files, so that anyone can regenerate them if they want to rebuild the appliance either via kiwi or via http://susestudio.com.

**Comment by aspiers** [comment]
BTW this will make @fghaas very happy too ;-)

**Comment by aspiers** [comment]
Oh yeah, please put this in the next milestone :)

**Comment by cseader** [comment]
closing due to new direction of adding DEPS ISO
