### ISSUE TITLE
eliminate copy'n'paste between setup-suse-crowbar*

### ISSUE THREAD

**Issue by aspiers** [cseader/suse-cloud-appliances#7]
There's a lot of code duplicated between `setup-suse-crowbar` and `setup-suse-crowbar_embedded`.  This should be extracted out into a separate library file which both appliances consume.

**Comment by cseader** [comment]
Thats a good idea.. I suppose I could check for /srv/tftpboot/txz folder and if there then do embedded tasks. I'll look into this.
